### ISSUE TITLE
Plugin not working when running in environment auto configured by metadata service

### ISSUE THREAD

**Issue by puco** [hypnoglow/helm-s3#15]
When I'm trying to install the plugin into our CI runner which runs inside AWS / EC2 / kubernetes and which gets assigned/assumes an IAM role I can't add a repository because there is no `~/aws/credentials` file. Even though s3 API / cli access is working.

### Repo steps:
```
$ aws s3 ls my-helm-bucket
> 2017-12-12 15:31:01        890 index.yaml

$ helm repo add private s3://my-helm-bucket
> 2017/12/12 15:41:25 get aws config: failed to parse aws credentials file: failed to open aws credentials file: open /root/.aws/credentials: no such file or directory
Error: Looks like "s3://my-helm-bucket" is not a valid chart repository or cannot be reached: plugin "bin/helms3" exited with error
```

**Comment by hypnoglow** [comment]
Hi!

Thank you, I've spotted a bug. I will provide a fix soon.

**Comment by hypnoglow** [comment]
@puco, the problem is fixed in version [0.4.3](https://github.com/hypnoglow/helm-s3/releases/tag/v0.4.3), please update the plugin.

Let me know if you run into any issues.

**Comment by puco** [comment]
Still not working:
```
# helm repo add test s3://my-helm-bucket
2017/12/13 09:52:32 fetch from s3: fetch object from s3: EmptyStaticCreds: static credentials are empty
Error: Looks like "s3://my-helm-bucket" is not a valid chart repository or cannot be reached: plugin "bin/helms3" exited with error
```

When I try to create some dummy `credentials` file it has precedence over the metadata service (which I currently don't know if it is correct or not)

**Comment by hypnoglow** [comment]
@puco , what are you trying to achieve? Why do you need to create dummy credentials file?
The bugfix was that specifying credentials file is not required anymore, but you still need to provide valid credentials using environment variables. 

> I'm trying to install the plugin into our CI runner which runs inside AWS / EC2 / kubernetes and which gets assigned/assumes an IAM role I can't add a repository

As I understood, you want to access S3 using EC2 Instance Roles. This feature is not supported by the plugin yet, but I think it should be easy for me to implement it.
